project:
  type: book

book:
  title: "AE 4803 AIM"
  author: "Elizabeth Qian, Atticus Rex, Pavlos Stavrinides"
  date: "Spring 2025"
  chapters:
    - index.qmd
    - 01_ls.qmd
    - 20_ugbo.qmd
    - 21_ugbo2.qmd
    # - intro.qmd
    # - summary.qmd
    # - references.qmd
  appendices:
    - 00_linalg.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



