project:
  type: book
  output-dir: docs

book:
  title: "AE 4803 AIM: Course Notes"
  author: "Elizabeth Qian, Atticus Rex, Pavlos Stavrinides"
  date: "Spring 2025"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 11_ls.qmd
    - 12_lslinalg.qmd
    # - 13_lsnla.qmd
    # - 20_ugbo.qmd
    # - 21_ugbo2.qmd
    - references.qmd
  appendices:
    - 00_linalg.qmd

bibliography: references.bib

number-sections: true

execute:
  freeze: auto

format:
  html:
    theme: cosmo
